---
services:
  code-server-user1:
    image: lscr.io/linuxserver/code-server:latest
    container_name: code-server-${USER1_NAME:-staging1}
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - PASSWORD=${USER1_PASSWORD:-ch4ng3m3}
      - SUDO_PASSWORD=${USER1_PASSWORD:-ch4ng3m3}
      - PROXY_DOMAIN=${USER1_NAME:-staging1}.geraldobtd.me
      - DEFAULT_WORKSPACE=/config/workspace
    volumes:
      # User 1 config
      - ${WORKDIR:-${PWD}}/config-${USER1_NAME:-staging1}:/config

      # User 1 workspace
      - ${WORKDIR:-${PWD}}/workspace-${USER1_NAME:-staging1}:/config/workspace

      # User 2 workspace
      - ${WORKDIR:-${PWD}}/workspace-${USER2_NAME:-staging2}:/config/workspace/${USER2_NAME:-staging2}-files:ro

      # General share directory
      - ${WORKDIR:-${PWD}}/share:/host_share:ro
    expose:
      - 8443
    restart: unless-stopped
    networks:
      - shared-network

  code-server-user2:
    image: lscr.io/linuxserver/code-server:latest
    container_name: code-server-${USER2_NAME:-staging2}
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - PASSWORD=${USER2_PASSWORD:-ch4ng3m3}
      - SUDO_PASSWORD=${USER2_PASSWORD:-ch4ng3m3}
      - PROXY_DOMAIN=${USER2_NAME:-staging2}.geraldobtd.me
      - DEFAULT_WORKSPACE=/config/workspace
    volumes:
      # User 2 config
      - ${WORKDIR:-${PWD}}/config-${USER2_NAME:-staging2}:/config

      # User 2 workspace
      - ${WORKDIR:-${PWD}}/workspace-${USER2_NAME:-staging2}:/config/workspace

      # User 1 workspace
      - ${WORKDIR:-${PWD}}/workspace-${USER1_NAME:-staging1}:/config/workspace/${USER1_NAME:-staging1}-files:ro

      # General share directory
      - ${WORKDIR:-${PWD}}/share:/host_share:ro
    expose:
      - 8443
    restart: unless-stopped
    networks:
      - shared-network

  caddy:
    image: caddy:2.9-alpine
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - $PWD/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - shared-network

networks:
  shared-network:
    external: true

volumes:
  caddy_data:
  caddy_config:
